// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNbwEjbq1KgRxzsWAQMnwhQLUhFTdkICU',
    appId: '1:586343572662:web:ce2432cb54d5ef5b5a3217',
    messagingSenderId: '586343572662',
    projectId: 'spend-flow-82e37',
    authDomain: 'spend-flow-82e37.firebaseapp.com',
    storageBucket: 'spend-flow-82e37.firebasestorage.app',
    measurementId: 'G-4W7YYCFV0B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrvLNYvtn3zj8qm33MgVG8_anUkb4W9fk',
    appId: '1:586343572662:android:aa19318e8dfe50365a3217',
    messagingSenderId: '586343572662',
    projectId: 'spend-flow-82e37',
    storageBucket: 'spend-flow-82e37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACMS8IKyi09SFJOv0s04BJbucW4b2Prg4',
    appId: '1:586343572662:ios:6228789e6b8ad4665a3217',
    messagingSenderId: '586343572662',
    projectId: 'spend-flow-82e37',
    storageBucket: 'spend-flow-82e37.firebasestorage.app',
    iosBundleId: 'com.example.spendFlow.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACMS8IKyi09SFJOv0s04BJbucW4b2Prg4',
    appId: '1:586343572662:ios:e9fd0ff992c9e8ee5a3217',
    messagingSenderId: '586343572662',
    projectId: 'spend-flow-82e37',
    storageBucket: 'spend-flow-82e37.firebasestorage.app',
    iosBundleId: 'com.example.spendFlow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNbwEjbq1KgRxzsWAQMnwhQLUhFTdkICU',
    appId: '1:586343572662:web:5f886046e50817565a3217',
    messagingSenderId: '586343572662',
    projectId: 'spend-flow-82e37',
    authDomain: 'spend-flow-82e37.firebaseapp.com',
    storageBucket: 'spend-flow-82e37.firebasestorage.app',
    measurementId: 'G-237K7Y999B',
  );
}
